### ISSUE TITLE
Affects composer window if popped up

### ISSUE THREAD

**Issue by veselov** [jparise/gmail-fixed-font#3]
To reproduce:

Start composing a new message. Verify the font is default (Sans-serif for me) in the composer body. You can enter text in the email body as well.
Pop-up the email window (shift + full-screen icon on the compose sub-window decor)
Click into the email body area, observe the font is now set to "Fixed Width"
It's a bit annoying afterwards as it seems to screw up the editor. To go back to original font, you have to select all the text, and change the font and the font size. Also, "clear formatting" button restores the text to fixed width.

Thank you :)

**Comment by jparise** [comment]
Which browser are you using?

**Comment by veselov** [comment]
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.125 Safari/537.36

I think it "just" got worse too :) Looks like gmail changed something. One one of my accounts I could see compose new mail start with fixed font, and on another it was fine (matched the settings). Then I reloaded the second account (browser window reload), and it started showing fixed font in compose window as well.

**Comment by jparise** [comment]
I'm not seeing this on any of my accounts (yet?). If you're able to figure out what's going on in the meantime and submit a patch, I'd be happy to look at it. Otherwise, I'll have to wait until I can see what changed first hand.

**Comment by veselov** [comment]
I think I'm being an idiot. The

    css += ".editable { font: medium monospace !important; }

line would set fixed width font for all new and empty compose windows by intent, right?

**Comment by jparise** [comment]
Yes, that's the idea.
