### ISSUE TITLE
change courier to other font

### ISSUE THREAD

**Issue by mihaicris** [jparise/gmail-fixed-font#4]
How can it be changed the default "monospace" font to something else?
For example I want to have the font displayed to "Liberation Mono, Bold, Size 9pt"
Can this be set in the script?

**Comment by jparise** [comment]
You can change the Chrome's monospace ("fixed width") font in the settings. This article describes how to do that in detail: http://www.pcadvisor.co.uk/how-to/software/how-change-font-in-google-chrome-3606119/
