### ISSUE TITLE
time to submit to openuserjs.org?

### ISSUE THREAD

**Issue by ryenus** [jparise/gmail-fixed-font#5]
https://openuserjs.org/ should be the new home to replace http://userscripts-mirror.org/scripts/show/17869, as shown [here][1].

[1]: https://webapps.stackexchange.com/questions/7438/can-you-make-gmail-show-plain-text-only-messages-in-fixed-width-font

**Comment by jparise** [comment]
Published as: https://openuserjs.org/scripts/jparise/Gmail_Fixed_Font

Thanks for the suggestion!

**Comment by ryenus** [comment]
👍
