### ISSUE TITLE
New GMail breaks the script.

### ISSUE THREAD

**Issue by toracat** [jparise/gmail-fixed-font#6]
It looks like the upcoming update to GMail breaks the script. Hope there is a way to fix this issue. I understand that Google will force the update in October, 2018.

**Comment by jparise** [comment]
@toracat please try the latest version. I hope it solves the problem.

**Comment by toracat** [comment]
@jparise 

A quick test shows it is working. Thank you so very much for you quick response. Much appreciated. I cannot live without fixed-width font. :)

Akemi
