### ISSUE TITLE
A shortcut to toggle fixed-width mode on/off

### ISSUE THREAD

**Issue by prati0100** [jparise/gmail-fixed-font#7]
Hi,

First of all, thanks for this script, its awesome.

I would like one feature though, the ability to turn on or off the fixed-width mode. Maybe a button or a keyboard shortcut? If you can do it, it would be much appreciated.

Regards,
Pratyush Yadav

**Comment by jparise** [comment]
I don't have any plans for that because it would be a lot more involved than the current very basis Greasemonkey script. If someone wanted to give it a spin, I'd be glad to review a pull request though!

**Comment by prati0100** [comment]
Well, I'm not a web developer, but I'll give it a shot. Thanks.
